export {default as DashBoardIcon} from './DashboardIcon.svg';
export {default as ScoreIcon} from './ScoreIcon.svg';
export {default as RecordIcon} from './RecordIcon.svg'; 
export {default as BasketballIcon} from './BasketballIcon.svg';
export {default as SoccerIcon} from './SoccerIcon.svg';
export {default as FootballIcon} from './FootballIcon.svg'; 
export {default as HockeyIcon} from './HockeyIcon.svg'; 
export {default as RightArrowIcon} from './RightArrowIcon.svg'
export {default as PlayIcon} from './PlayIcon.svg'
export {default as PauseIcon} from './PauseIcon.svg'
export {default as CancelIcon} from './CancelIcon.svg'
export {default as DownArrowIcon} from './DownArrowIcon.svg'