export { default as DashBoardIcon } from './DashboardIcon.svg';
export { default as ScoreIcon } from './ScoreIcon.svg';
export { default as RecordIcon } from './RecordIcon.svg';
export { default as BasketballIcon } from './BasketballIcon.svg';
export { default as SoccerIcon } from './SoccerIcon.svg';
export { default as FootballIcon } from './FootballIcon.svg';
export { default as HockeyIcon } from './HockeyIcon.svg';
export { default as RightArrowIcon } from './RightArrowIcon.svg'
export { default as PlayIcon } from './PlayIcon.svg'
export { default as PauseIcon } from './PauseIcon.svg'
export { default as CancelIcon } from './CancelIcon.svg'
export {default as DownArrowIcon} from './DownArrowIcon.svg'
export { default as BasketballBlockIcon } from './BasketballBlockIcon.svg'
export { default as BrickWallIcon } from './BrickWallIcon.svg'
export { default as BugIcon } from './BugIcon.svg'
export { default as ClockIcon } from './ClockIcon.svg'
export { default as FootballCatchIcon } from './FootballCatchIcon.svg'
export { default as FootballPickupIcon } from './FootballPickupIcon.svg'
export { default as MeasuringTapeIcon } from './MeasuringTapeIcon.svg'
export { default as PassIcon } from './PassIcon.svg'
export { default as PinIcon } from './PinIcon.svg'
export { default as SaveGoalIcon } from './SaveGoalIcon.svg'
export { default as StealIcon } from './StealIcon.svg'
export { default as TurnoverIcon } from './SwapArrowIcon.svg'
export { default as SwordsIcon } from './SwordsIcon.svg'
export { default as TargetIcon } from './TargetIcon.svg'
export { default as WinningCardIcon } from './WarningCardIcon.svg'
export { default as AssistIcon } from './AssistIcon.svg'