import Head from 'next/head';
import styles from '../styles/Dashboard.module.css';
import {GetServerSideProps} from 'next/types';
import {getSession} from 'next-auth/react';

export default function DashBoard() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context);
  console.log(session)
  if (!session) return {
    props: {},
    redirect: {destination: '/login'}
  };

  return {props: {session}};
};
